name: Workflow Template

on:
  workflow_call:
    inputs:
      base-image:
        required: false
        type: string
        default: '["ubuntu","redhat/ubi9"]'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJson(inputs.base-image) }}
    steps:
      - name: Pull image
        run: docker pull ${{ matrix.image }}
